version: "3.9"

services:
  book:
    image: book:01
    container_name: book-service
    ports:
      - "8083:8080"
    networks:
      - library-net
    restart: always

  member:
    image: member:01
    container_name: member-service
    ports:
      - "8090:8081"
    networks:
      - library-net
    restart: always

networks:
  library-net:
    driver: bridge
