apiVersion: apps/v1
kind: Deployment
metadata:
  name: book
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book
  template:
    metadata:
      labels:
        app: book
    spec:
      containers:
        - name: book
          image: book:01
          ports:
            - containerPort: 8080
