apiVersion: apps/v1
kind: Deployment
metadata:
  name: library-backend
  labels:
    app: library-reactive
spec:
  replicas: 2
  selector:
    matchLabels:
      app: library-reactive
  template:
    metadata:
      labels:
        app: library-reactive
    spec:
      containers:
        - name: library-reactive
          image: library-reactive:0.1.0
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: k8s